##
# Kubernetes configuration for setting up all of the persistent volume claims
# for Nextcloud to store its configuration, apps, and themes on Azure Blob
# storage.
#
# These must exactly match the claims in `blob-volumes.template.yaml`. Claims are
# being used to allow storage to be portable across pods.
#
# @author Guy Elsmore-Paddock (guy@inveniem.com)
# @copyright Copyright (c) 2019, Inveniem
# @license GNU AGPL version 3 or any later version
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nextcloud-config
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: vol-nextcloud-blob-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nextcloud-themes
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: vol-nextcloud-blob-themes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nextcloud-apps
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: vol-nextcloud-blob-apps
