##
# Kubernetes template used to set up each Azure File share that Nextcloud uses
# to store client data and uploads, via a persistent volume claim and its
# corresponding Azure-Files-based persistent volume.
#
# Although more expensive (by a factor of 6), Azure Files is higher throughput
# than Azure Blob storage and safe for access by multiple pods in the same
# cluster.
#
# NOTE: `${file_share_name}` assumes the name of each file share defined in the
# configuration.
#
#
# @author Guy Elsmore-Paddock (guy@inveniem.com)
# @copyright Copyright (c) 2019, Inveniem
# @license GNU AGPL version 3 or any later version
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "vol-nextcloud-share-${file_share_name}"
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: "${KUBE_FILES_STORAGE_ACCOUNT_SECRET}"
    shareName: "${file_share_name}"
    readOnly: false
  mountOptions:
    - uid=33
    - gid=33
    - dir_mode=0770
    - file_mode=0770
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "claim-nextcloud-${file_share_name}"
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: "vol-nextcloud-share-${file_share_name}"
---
