apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-blob-nextcloud-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/blobfuse"
    secretRef:
      name: "${KUBE_STORAGE_ACCOUNT_SECRET}"
    options:
      container: nextcloud-config
      tmppath: /tmp/blobfuse/nextcloud-config
      mountoptions: "-o uid=33 -o gid=33 -o allow_other -o umask=007 --file-cache-timeout-in-seconds=120"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-blob-nextcloud-themes
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/blobfuse"
    secretRef:
      name: "${KUBE_STORAGE_ACCOUNT_SECRET}"
    options:
      container: nextcloud-themes
      tmppath: /tmp/blobfuse/nextcloud-themes
      mountoptions: "-o uid=33 -o gid=33 -o allow_other -o umask=007 --file-cache-timeout-in-seconds=120"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-blob-nextcloud-apps
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/blobfuse"
    secretRef:
      name: "${KUBE_STORAGE_ACCOUNT_SECRET}"
    options:
      container: nextcloud-apps
      tmppath: /tmp/blobfuse/nextcloud-apps
      mountoptions: "-o uid=33 -o gid=33 -o allow_other -o umask=007 --file-cache-timeout-in-seconds=120"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-blob-nextcloud-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/blobfuse"
    secretRef:
      name: "${KUBE_STORAGE_ACCOUNT_SECRET}"
    options:
      container: nextcloud-data
      tmppath: /tmp/blobfuse/nextcloud-data
      mountoptions: "-o uid=33 -o gid=33 -o allow_other -o umask=007 --file-cache-timeout-in-seconds=120"
