apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-admin-creds
type: Opaque
stringData:
  username: "${NEXTCLOUD_ADMIN_USER}"
  password: "${NEXTCLOUD_ADMIN_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-mysql-connection-creds
type: Opaque
stringData:
  hostname: "${MYSQL_HOST}"
  database: "${MYSQL_DATABASE}"
  username: "${MYSQL_USER}"
  password: "${MYSQL_PASSWORD}"
