apiVersion: v1
kind: Secret
metadata:
  name: "${KUBE_NEXTCLOUD_ADMIN_CREDS_SECRET}"
type: Opaque
stringData:
  username: "${NEXTCLOUD_ADMIN_USER}"
  password: "${NEXTCLOUD_ADMIN_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "${KUBE_NEXTCLOUD_MYSQL_CREDS_SECRET}"
type: Opaque
stringData:
  hostname: "${MYSQL_HOST}"
  database: "${MYSQL_DATABASE}"
  username: "${MYSQL_USER}"
  password: "${MYSQL_PASSWORD}"
