##
# Kubernetes configuration for setting up a persistent volume for Nextcloud to
# store its configuration on Azure Blob storage.
#
# @author Guy Elsmore-Paddock (guy@inveniem.com)
# @copyright Copyright (c) 2019, Inveniem
# @license GNU AGPL version 3 or any later version
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-nextcloud-blob-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/blobfuse"
    secretRef:
      name: "${KUBE_BLOB_STORAGE_ACCOUNT_SECRET}"
    options:
      container: nextcloud-config
      tmppath: /mnt/blobfusetmp/nextcloud-config
      mountoptions: "-o uid=33 -o gid=33 -o allow_other -o umask=007 --file-cache-timeout-in-seconds=120"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nextcloud-config
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: vol-nextcloud-blob-config
