##
# Kubernetes deployment configuration for running an SFTP-WS alongside
# Nextcloud for one or more shares.
#
# @author Guy Elsmore-Paddock (guy@inveniem.com)
# @copyright Copyright (c) 2019, Inveniem
# @license GNU AGPL version 3 or any later version
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-ws-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend-sftp-ws-server
  template:
    metadata:
      labels:
        app: backend-sftp-ws-server
        role: backend
    spec:
      containers:
        # Container: The SFTP-WS server.
        - name: backend-sftp-ws-server
          image: "${REGISTRY_HOST}/inveniem/sftp-ws-server:latest"
          ports:
            - containerPort: 4002
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
            # HACK: Until AKS supports pod presets, we have to kludge the dynamic
            # mounts in via a variable expansion. Do not modify the last line of
            # this comment; it gets expanded and replaced automatically when this
            # file is pre-processed. Remove this entire comment when switching over
            # to using pod presets.
            #
            # ${FILE_SHARE_VOLUME_MOUNT_LINES}
          env:
            - name: SFTP_WS_HOST
              value: "0.0.0.0"
            - name: SFTP_WS_PORT
              value: "4002"
            - name: SFTP_WS_APP_HOST
              value: "${NEXTCLOUD_PRIMARY_HOSTNAME}"
            - name: SFTP_WS_ORIGIN_RESTRICTIONS
              value: '${SFTP_WS_ORIGIN_RESTRICTIONS}'
      imagePullSecrets:
        # NOTE: This secret is added by `setup_aks_acr_service_principal.sh`.
        - name: "${ACR_DOCKER_CREDS_SECRET}"
      volumes:
        # HACK: Until AKS supports pod presets, we have to kludge the dynamic
        # mounts in via a variable expansion. Do not modify the last line of
        # this comment; it gets expanded and replaced automatically when this
        # file is pre-processed. Remove this entire comment when switching over
        # to using pod presets.
        #
        # ${FILE_SHARE_VOLUME_LINES}
---
apiVersion: v1
kind: Service
metadata:
  name: internal-sftp-ws-server
  labels:
    role: internal-service
spec:
  type: ClusterIP
  ports:
    - port: 4002
  selector:
    app: backend-sftp-ws-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-sftp-ws-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: "/sftp"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
spec:
  tls:
    - hosts:
        - "${NEXTCLOUD_PRIMARY_HOSTNAME}"
      secretName: nextcloud-tls-certificate
  rules:
    - host: "${NEXTCLOUD_PRIMARY_HOSTNAME}"
      http:
        paths:
          - path: /sftp
            backend:
              serviceName: internal-sftp-ws-server
              servicePort: 4002
