apiVersion: v1
kind: Secret
metadata:
  name: "${KUBE_REDIS_AUTH_SECRET}"
type: Opaque
stringData:
  password: "${REDIS_AUTH_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "${KUBE_REDIS_CONFIG_SECRET}"
stringData:
  redis.conf: |
    maxmemory 496mb
    maxmemory-policy allkeys-lru

    requirepass "${REDIS_AUTH_PASSWORD}"
